version: '3.8'

services:

  #------------------------ DB & Kafka ------------------------

  # БД для stats сервиса
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"

  # БД для event сервиса
  event-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "6543:5432"

  # общий сервер для БД микросервисов
  microservices-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: frosty
      POSTGRES_PASSWORD: ytsorf
    ports:
      - "6767:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

  #------------------------ Spring Cloud Infrastructure ------------------------

  discovery-server:
    build:
      context: .
      dockerfile: infra/discovery-server/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5

  config-server:
    build:
      context: .
      dockerfile: infra/config-server/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native,docker
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      # 15 секунд, иначе не факт, что config-server кэшируется в eureka
      # зависит от eureka.client.registryFetchIntervalSeconds: X
      # в config-server/resources/config/infra/discovery-server/discovery-server-default.yml
      interval: 15s
      timeout: 3s
      retries: 5

  gateway-server:
    build:
      context: .
      dockerfile: infra/gateway-server/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 3s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy

  #------------------------ Applications ------------------------

  # stats сервис
  stats-server:
    build:
      context: .
      dockerfile: stats/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    depends_on:
      config-server:
        condition: service_healthy

  # event сервис
  event-service:
    build:
      context: .
      dockerfile: core/event-service/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/event
      SPRING_DATASOURCE_USERNAME: main
      SPRING_DATASOURCE_PASSWORD: main
    depends_on:
      config-server:
        condition: service_healthy

  # user сервис
  user-service:
    build:
      context: .
      dockerfile: core/user-service/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://microservices:5432/core_users
      SPRING_DATASOURCE_USERNAME: frosty
      SPRING_DATASOURCE_PASSWORD: ytsorf
    depends_on:
      config-server:
        condition: service_healthy

  # request сервис
  request-service:
    build:
      context: .
      dockerfile: core/request-service/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://microservices:5432/core_requests
      SPRING_DATASOURCE_USERNAME: frosty
      SPRING_DATASOURCE_PASSWORD: ytsorf
    depends_on:
      config-server:
        condition: service_healthy

  # comment сервис
  comment-service:
    build:
      context: .
      dockerfile: core/comment-service/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://microservices:5432/core_comments
      SPRING_DATASOURCE_USERNAME: frosty
      SPRING_DATASOURCE_PASSWORD: ytsorf
    depends_on:
      config-server:
        condition: service_healthy